import { InvestigationOrdersPageData } from "@/types/doctor/ipd/investigation-order-types";


export const INVESTIGATION_ORDERS_DATA: Record<string, InvestigationOrdersPageData> = {
  UHID12345685: {
    items: [
      {
        id: "INV1",
        investigationName: "Complete Blood Count (CBC)",
        category: "Hematology",
        priority: "Routine",
        sample: "EDTA Whole Blood",
        orderDate: "20 May 2024, 11:20 AM",
        status: "Sample Collected",
        results: "Pending",
        indication: "Evaluation of general health status",
        additionalInstructions: "",
        fastingRequired: "No",
        timing: "Anytime",
        reportUrgency: "Routine",
        expectedReportTime: "24 Hours",
        repeatAfter: "",
        saveAsFavorite: false,
      },
      {
        id: "INV2",
        investigationName: "Liver Function Test (LFT)",
        category: "Biochemistry",
        priority: "Routine",
        sample: "Serum",
        orderDate: "20 May 2024, 11:20 AM",
        status: "Sample Collected",
        results: "Pending",
        indication: "Monitoring of ongoing treatment",
        additionalInstructions: "",
        fastingRequired: "No",
        timing: "Anytime",
        reportUrgency: "Routine",
        expectedReportTime: "24 Hours",
        repeatAfter: "",
        saveAsFavorite: false,
      },
      {
        id: "INV3",
        investigationName: "Serum Electrolytes (Na, K, Cl)",
        category: "Biochemistry",
        priority: "Routine",
        sample: "Serum",
        orderDate: "20 May 2024, 11:20 AM",
        status: "Ordered",
        results: "Pending",
        indication: "Assessment of electrolyte balance",
        additionalInstructions: "",
        fastingRequired: "No",
        timing: "Anytime",
        reportUrgency: "Routine",
        expectedReportTime: "24 Hours",
        repeatAfter: "",
        saveAsFavorite: false,
      },
      {
        id: "INV4",
        investigationName: "ECG (12 Lead)",
        category: "Cardiology",
        priority: "Routine",
        sample: "—",
        orderDate: "20 May 2024, 11:20 AM",
        status: "Completed",
        results: "View Report",
        indication: "Cardiac evaluation",
        additionalInstructions: "",
        fastingRequired: "Not Applicable",
        timing: "Anytime",
        reportUrgency: "Routine",
        expectedReportTime: "Immediate",
        repeatAfter: "",
        saveAsFavorite: false,
      },
      {
        id: "INV5",
        investigationName: "Chest X-Ray (PA View)",
        category: "Radiology",
        priority: "High",
        sample: "—",
        orderDate: "20 May 2024, 11:20 AM",
        status: "Ordered",
        results: "Pending",
        indication: "Chest pain / respiratory evaluation",
        additionalInstructions: "",
        fastingRequired: "Not Applicable",
        timing: "Anytime",
        reportUrgency: "Urgent",
        expectedReportTime: "2 Hours",
        repeatAfter: "",
        saveAsFavorite: false,
      },
    ],
    indication: "Evaluation of general health status and monitoring of ongoing treatment.",
    instructions: "Please ensure patient is fasting for 8–10 hours for LFT. Collect samples in the morning.",
  },
};

export const INVESTIGATION_SUGGESTIONS = [
  "HbA1c (Glycated Hemoglobin)",
  "Thyroid Profile (T3, T4, TSH)",
  "Urine Routine & Microscopy",
  "CT Scan Brain (Plain)",
  "Vitamin D (25-OH)",
  "Complete Blood Count (CBC)",
  "Liver Function Test (LFT)",
  "Serum Electrolytes (Na, K, Cl)",
];

export function getInvestigationOrdersData(uhid: string): InvestigationOrdersPageData {
  return INVESTIGATION_ORDERS_DATA[uhid] ?? INVESTIGATION_ORDERS_DATA.UHID12345685;
}