
import type { MedicineOrdersPageData } from "@/types/doctor/ipd/medicine-order-types";

export const MEDICINE_ORDERS_DATA: Record<string, MedicineOrdersPageData> = {
  UHID12345685: {
    items: [
      {
        id: "MO1",
        medicineName: "Tab. Ecosprin AV",
        strengthForm: "75 mg",
        dose: "75 mg",
        route: "Oral",
        frequency: "OD (Once a day)",
        duration: "5 Days",
        startDate: "20 May 2024",
        endDate: "24 May 2024",
        timing: ["After Food"],
        instructions: "After breakfast",
        specialInstructions: "",
        indication: "Stable Angina",
        category: "Antiplatelet",
        saveAsFavorite: false,
        status: "Active",
      },
      {
        id: "MO2",
        medicineName: "Tab. Atorvastatin",
        strengthForm: "20 mg",
        dose: "20 mg",
        route: "Oral",
        frequency: "OD (Once a day)",
        duration: "30 Days",
        startDate: "20 May 2024",
        endDate: "18 Jun 2024",
        timing: ["At Night"],
        instructions: "At bedtime",
        specialInstructions: "",
        indication: "Hyperlipidemia",
        category: "Statin",
        saveAsFavorite: false,
        status: "Active",
      },
      {
        id: "MO3",
        medicineName: "Tab. Telmisartan",
        strengthForm: "40 mg",
        dose: "40 mg",
        route: "Oral",
        frequency: "OD (Once a day)",
        duration: "30 Days",
        startDate: "20 May 2024",
        endDate: "18 Jun 2024",
        timing: ["After Food"],
        instructions: "After breakfast",
        specialInstructions: "",
        indication: "Hypertension",
        category: "Antihypertensive",
        saveAsFavorite: false,
        status: "Active",
      },
      {
        id: "MO4",
        medicineName: "Tab. Clopidogrel",
        strengthForm: "75 mg",
        dose: "75 mg",
        route: "Oral",
        frequency: "OD (Once a day)",
        duration: "30 Days",
        startDate: "20 May 2024",
        endDate: "18 Jun 2024",
        timing: ["After Food"],
        instructions: "After breakfast",
        specialInstructions: "",
        indication: "Stable Angina",
        category: "Antiplatelet",
        saveAsFavorite: false,
        status: "Active",
      },
      {
        id: "MO5",
        medicineName: "Tab. Pantoprazole",
        strengthForm: "40 mg",
        dose: "40 mg",
        route: "Oral",
        frequency: "OD (Once a day)",
        duration: "30 Days",
        startDate: "20 May 2024",
        endDate: "18 Jun 2024",
        timing: ["Before Food"],
        instructions: "Before breakfast",
        specialInstructions: "",
        indication: "Gastric Protection",
        category: "PPI",
        saveAsFavorite: false,
        status: "Active",
      },
    ],
    notes: "Monitor BP daily. Report any episode of chest pain / breathlessness immediately.",
    allergies: "No known drug allergies",
    preferredPharmacy: "Leads Hospital Pharmacy",
  },
};

export const MEDICINE_SUGGESTIONS = [
  "Paracetamol 500 mg Tablet",
  "Paracetamol 650 mg Tablet",
  "Azithromycin 500 mg Tablet",
  "Pantoprazole 40 mg Tablet",
  "Telmisartan 40 mg Tablet",
  "Atorvastatin 20 mg Tablet",
  "Clopidogrel 75 mg Tablet",
  "Ecosprin AV 75 mg Capsule",
];

export function getMedicineOrdersData(uhid: string): MedicineOrdersPageData {
  return MEDICINE_ORDERS_DATA[uhid] ?? MEDICINE_ORDERS_DATA.UHID12345685;
}