// lib/admission-request-data.ts
import type { AdmissionRequestRecord } from "@/types/admission-request-types";

export const ADMISSION_REQUESTS: AdmissionRequestRecord[] = [
  { requestId: "REQ240520-0018", requestDateTime: "20 May 2024, 10:25 AM", patientName: "Ravi Sharma", uhid: "UHID12345685", age: 48, gender: "Male", department: "Cardiology", attendingDoctor: "Dr. Amit Verma", requestedByLocation: "OPD - Room 12", requestedByDoctor: "Dr. Amit Verma", requestStatus: "Pending Review", priority: "High" },
  { requestId: "REQ240520-0017", requestDateTime: "20 May 2024, 09:45 AM", patientName: "Neha Singh", uhid: "UHID12345684", age: 36, gender: "Female", department: "General Medicine", attendingDoctor: "Dr. Priya Nair", requestedByLocation: "OPD - Room 05", requestedByDoctor: "Dr. Priya Nair", requestStatus: "Pending Review", priority: "Medium" },
  { requestId: "REQ240520-0016", requestDateTime: "20 May 2024, 08:50 AM", patientName: "Suresh Yadav", uhid: "UHID12345683", age: 55, gender: "Male", department: "General Surgery", attendingDoctor: "Dr. Rahul Mehta", requestedByLocation: "OPD - Room 08", requestedByDoctor: "Dr. Rahul Mehta", requestStatus: "Approved", priority: "High" },
  { requestId: "REQ240520-0015", requestDateTime: "20 May 2024, 08:15 AM", patientName: "Pooja Verma", uhid: "UHID12345682", age: 29, gender: "Female", department: "Obstetrics & Gynae", attendingDoctor: "Dr. Neha Bansal", requestedByLocation: "OPD - Room 03", requestedByDoctor: "Dr. Neha Bansal", requestStatus: "Approved", priority: "Medium" },
  { requestId: "REQ240519-0014", requestDateTime: "19 May 2024, 07:10 PM", patientName: "Mohd. Faizan", uhid: "UHID12345680", age: 41, gender: "Male", department: "ENT", attendingDoctor: "Dr. Sameer Khan", requestedByLocation: "OPD - Room 11", requestedByDoctor: "Dr. Sameer Khan", requestStatus: "Pending Review", priority: "Low" },
  { requestId: "REQ240519-0013", requestDateTime: "19 May 2024, 06:30 PM", patientName: "Anjali Mehta", uhid: "UHID12345679", age: 34, gender: "Female", department: "Dermatology", attendingDoctor: "Dr. Richa Sharma", requestedByLocation: "OPD - Room 07", requestedByDoctor: "Dr. Richa Sharma", requestStatus: "Approved", priority: "Medium" },
  { requestId: "REQ240519-0012", requestDateTime: "19 May 2024, 04:55 PM", patientName: "Vikram Singh", uhid: "UHID12345678", age: 52, gender: "Male", department: "Orthopedics", attendingDoctor: "Dr. Puneet Arora", requestedByLocation: "OPD - Room 09", requestedByDoctor: "Dr. Puneet Arora", requestStatus: "Rejected", priority: "High" },
  { requestId: "REQ240519-0011", requestDateTime: "19 May 2024, 03:40 PM", patientName: "Meena Kapoor", uhid: "UHID12345677", age: 37, gender: "Female", department: "Pediatrics", attendingDoctor: "Dr. Pooja Iyer", requestedByLocation: "OPD - Room 10", requestedByDoctor: "Dr. Pooja Iyer", requestStatus: "Pending Review", priority: "Low" },
  { requestId: "REQ240519-0010", requestDateTime: "19 May 2024, 02:25 PM", patientName: "Harish Patel", uhid: "UHID12345676", age: 60, gender: "Male", department: "Neurology", attendingDoctor: "Dr. Vivek Chandra", requestedByLocation: "OPD - Room 06", requestedByDoctor: "Dr. Vivek Chandra", requestStatus: "Pending Review", priority: "High" },
  { requestId: "REQ240519-0009", requestDateTime: "19 May 2024, 11:20 AM", patientName: "Sunita Devi", uhid: "UHID12345675", age: 38, gender: "Female", department: "General Surgery", attendingDoctor: "Dr. Rahul Mehta", requestedByLocation: "OPD - Room 08", requestedByDoctor: "Dr. Rahul Mehta", requestStatus: "Rejected", priority: "Low" },
  { requestId: "REQ240519-0008", requestDateTime: "19 May 2024, 10:05 AM", patientName: "Deepak Gupta", uhid: "UHID12345674", age: 47, gender: "Male", department: "General Medicine", attendingDoctor: "Dr. Priya Nair", requestedByLocation: "OPD - Room 05", requestedByDoctor: "Dr. Priya Nair", requestStatus: "Approved", priority: "Medium" },
  { requestId: "REQ240519-0007", requestDateTime: "19 May 2024, 09:00 AM", patientName: "Kavita Joshi", uhid: "UHID12345673", age: 31, gender: "Female", department: "ENT", attendingDoctor: "Dr. Sameer Khan", requestedByLocation: "OPD - Room 11", requestedByDoctor: "Dr. Sameer Khan", requestStatus: "Rejected", priority: "Medium" },
  { requestId: "REQ240518-0006", requestDateTime: "18 May 2024, 04:15 PM", patientName: "Rohit Malhotra", uhid: "UHID12345672", age: 44, gender: "Male", department: "Cardiology", attendingDoctor: "Dr. Amit Verma", requestedByLocation: "OPD - Room 12", requestedByDoctor: "Dr. Amit Verma", requestStatus: "Approved", priority: "High" },
  { requestId: "REQ240518-0005", requestDateTime: "18 May 2024, 03:00 PM", patientName: "Simran Kaur", uhid: "UHID12345671", age: 27, gender: "Female", department: "Obstetrics & Gynae", attendingDoctor: "Dr. Neha Bansal", requestedByLocation: "OPD - Room 03", requestedByDoctor: "Dr. Neha Bansal", requestStatus: "Pending Review", priority: "Medium" },
  { requestId: "REQ240518-0004", requestDateTime: "18 May 2024, 01:45 PM", patientName: "Arjun Reddy", uhid: "UHID12345670", age: 50, gender: "Male", department: "Orthopedics", attendingDoctor: "Dr. Puneet Arora", requestedByLocation: "OPD - Room 09", requestedByDoctor: "Dr. Puneet Arora", requestStatus: "Approved", priority: "Low" },
  { requestId: "REQ240518-0003", requestDateTime: "18 May 2024, 12:30 PM", patientName: "Priyanka Nair", uhid: "UHID12345669", age: 33, gender: "Female", department: "Dermatology", attendingDoctor: "Dr. Richa Sharma", requestedByLocation: "OPD - Room 07", requestedByDoctor: "Dr. Richa Sharma", requestStatus: "Pending Review", priority: "Low" },
  { requestId: "REQ240518-0002", requestDateTime: "18 May 2024, 11:15 AM", patientName: "Manoj Tiwari", uhid: "UHID12345668", age: 58, gender: "Male", department: "Neurology", attendingDoctor: "Dr. Vivek Chandra", requestedByLocation: "OPD - Room 06", requestedByDoctor: "Dr. Vivek Chandra", requestStatus: "Rejected", priority: "High" },
  { requestId: "REQ240518-0001", requestDateTime: "18 May 2024, 10:00 AM", patientName: "Divya Menon", uhid: "UHID12345667", age: 30, gender: "Female", department: "Pediatrics", attendingDoctor: "Dr. Pooja Iyer", requestedByLocation: "OPD - Room 10", requestedByDoctor: "Dr. Pooja Iyer", requestStatus: "Pending Review", priority: "Medium" },
];

export const REQUEST_DEPARTMENTS = Array.from(new Set(ADMISSION_REQUESTS.map((r) => r.department)));
export const REQUEST_DOCTORS = Array.from(new Set(ADMISSION_REQUESTS.map((r) => r.attendingDoctor)));