
import type { BedOccupiedPatient } from "@/types/nurse/ipd/bed-occupied-types";

export const BED_OCCUPIED_PATIENTS: BedOccupiedPatient[] = [
  {
    id: "1",
    admissionId: "IPD240520001",
    uhid: "UHID12345685",
    patientName: "Ravi Sharma",
    age: 48,
    gender: "Male",
    bloodGroup: "B+",
    ward: "Semi Private",
    room: "Room-2",
    bed: "B-203",
    department: "Cardiology",
    admittingDoctor: "Dr. Amit Verma",
    occupiedOn: "20 May 2024, 11:20 AM",
    status: "Stable",
    occupiedBy: "Neha Singh (Staff Nurse)",
    emergencyContactName: "Suresh Sharma (Brother)",
    emergencyContactPhone: "9876501234",
    packageName: "Cardiology Care Package",
    initialAssessment: "Pending",
    vitalsRecording: "Pending",
    nursingAssessment: "Pending",
  },
  {
    id: "2",
    admissionId: "IPD240520002",
    uhid: "UHID12345686",
    patientName: "Sunita Devi",
    age: 60,
    gender: "Female",
    bloodGroup: "O+",
    ward: "General Ward",
    room: "Room-5",
    bed: "G-105",
    department: "Neurology",
    admittingDoctor: "Dr. Priya Nair",
    occupiedOn: "20 May 2024, 10:45 AM",
    status: "Stable",
    occupiedBy: "Priyanka Das (Staff Nurse)",
    emergencyContactName: "Rajesh Devi (Son)",
    emergencyContactPhone: "9812345670",
    packageName: "Neuro Observation",
    initialAssessment: "Pending",
    vitalsRecording: "Pending",
    nursingAssessment: "Pending",
  },
  {
    id: "3",
    admissionId: "IPD240520003",
    uhid: "UHID12345687",
    patientName: "Mohd. Irfan",
    age: 55,
    gender: "Male",
    bloodGroup: "A+",
    ward: "Semi Private",
    room: "Room-3",
    bed: "B-205",
    department: "Orthopedics",
    admittingDoctor: "Dr. Rajesh Iyer",
    occupiedOn: "20 May 2024, 09:30 AM",
    status: "Observation",
    occupiedBy: "Anjali Mehta (Staff Nurse)",
    emergencyContactName: "Nasreen Irfan (Wife)",
    emergencyContactPhone: "9876509990",
    packageName: "Ortho Trauma Package",
    initialAssessment: "Completed",
    vitalsRecording: "Pending",
    nursingAssessment: "Pending",
  },
  {
    id: "4",
    admissionId: "IPD240520004",
    uhid: "UHID12345688",
    patientName: "Neha Gupta",
    age: 32,
    gender: "Female",
    bloodGroup: "AB+",
    ward: "General Ward",
    room: "Room-4",
    bed: "G-107",
    department: "Gynecology",
    admittingDoctor: "Dr. Anjali Mehta",
    occupiedOn: "20 May 2024, 08:50 AM",
    status: "Stable",
    occupiedBy: "Kavita Rao (Staff Nurse)",
    emergencyContactName: "Rakesh Gupta (Husband)",
    emergencyContactPhone: "9898981111",
    packageName: "Maternity Care Package",
    initialAssessment: "Completed",
    vitalsRecording: "Completed",
    nursingAssessment: "Pending",
  },
  {
    id: "5",
    admissionId: "IPD240520005",
    uhid: "UHID12345689",
    patientName: "Arun Kumar",
    age: 67,
    gender: "Male",
    bloodGroup: "O-",
    ward: "Semi Private",
    room: "Room-1",
    bed: "B-201",
    department: "General Medicine",
    admittingDoctor: "Dr. Sandeep Rao",
    occupiedOn: "19 May 2024, 07:15 PM",
    status: "Critical",
    occupiedBy: "Meenakshi Nair (Staff Nurse)",
    emergencyContactName: "Anita Kumar (Wife)",
    emergencyContactPhone: "9811002200",
    packageName: "Senior Medical Support",
    initialAssessment: "Completed",
    vitalsRecording: "Pending",
    nursingAssessment: "Pending",
  },
  {
    id: "6",
    admissionId: "IPD240520006",
    uhid: "UHID12345690",
    patientName: "Pooja Singh",
    age: 28,
    gender: "Female",
    bloodGroup: "A+",
    ward: "Semi Private",
    room: "Room-2",
    bed: "B-204",
    department: "Dermatology",
    admittingDoctor: "Dr. Meera Kapoor",
    occupiedOn: "19 May 2024, 06:40 PM",
    status: "Stable",
    occupiedBy: "Neha Singh (Staff Nurse)",
    emergencyContactName: "Amit Singh (Brother)",
    emergencyContactPhone: "9822003344",
    packageName: "Skin Care Package",
    initialAssessment: "Completed",
    vitalsRecording: "Completed",
    nursingAssessment: "Completed",
  },
];