
import type { WardArrivalPatient } from "@/types/nurse/ipd/patient-arrives-types";

export const NURSE_WARD_PATIENTS: WardArrivalPatient[] = [
  {
    id: "1",
    admissionId: "IPD240520001",
    uhid: "UHID12345685",
    patientName: "Ravi Sharma",
    age: 48,
    gender: "Male",
    ward: "Semi Private",
    room: "Room-2",
    bed: "B-203",
    department: "Cardiology",
    admittingDoctor: "Dr. Amit Verma",
    arrivalStatus: "Awaiting Acceptance",
    admissionDateTime: "20 May 2024, 11:30 AM",
    packageName: "Cardiology Care Package",
    emergencyContactName: "Suresh Sharma (Brother)",
    emergencyContactPhone: "9876501234",
    bloodGroup: "B+",
    alerts: ["Drug Allergy", "Fall Risk", "Diabetic", "Insurance Verified"],
    transferChecklist: {
      admissionConfirmed: true,
      depositReceived: true,
      bedAllocated: true,
      documentsVerified: true,
      wristbandGenerated: false,
      initialAssessmentPending: true,
    },
  },
  {
    id: "2",
    admissionId: "IPD240520002",
    uhid: "UHID12345686",
    patientName: "Sunita Devi",
    age: 60,
    gender: "Female",
    ward: "General Ward",
    room: "Room-5",
    bed: "G-105",
    department: "Neurology",
    admittingDoctor: "Dr. Priya Nair",
    arrivalStatus: "Awaiting Acceptance",
    admissionDateTime: "20 May 2024, 11:45 AM",
    packageName: "Neuro Observation",
    emergencyContactName: "Rajesh Devi (Son)",
    emergencyContactPhone: "9812345670",
    bloodGroup: "O+",
    alerts: ["Fall Risk"],
    transferChecklist: {
      admissionConfirmed: true,
      depositReceived: true,
      bedAllocated: true,
      documentsVerified: true,
      wristbandGenerated: false,
      initialAssessmentPending: true,
    },
  },
  {
    id: "3",
    admissionId: "IPD240520003",
    uhid: "UHID12345687",
    patientName: "Mohd. Irfan",
    age: 55,
    gender: "Male",
    ward: "Semi Private",
    room: "Room-3",
    bed: "B-205",
    department: "Orthopedics",
    admittingDoctor: "Dr. Rajesh Iyer",
    arrivalStatus: "Awaiting Acceptance",
    admissionDateTime: "20 May 2024, 12:00 PM",
    packageName: "Ortho Trauma Package",
    emergencyContactName: "Nasreen Irfan (Wife)",
    emergencyContactPhone: "9876509990",
    bloodGroup: "A+",
    alerts: ["Diabetic"],
    transferChecklist: {
      admissionConfirmed: true,
      depositReceived: true,
      bedAllocated: true,
      documentsVerified: true,
      wristbandGenerated: false,
      initialAssessmentPending: true,
    },
  },
];

export const RECEIVING_NURSES = [
  "Neha Singh",
  "Priyanka Das",
  "Anjali Mehta",
  "Kavita Rao",
  "Meenakshi Nair",
];